### PR TITLE
Feature/nav header - A draft Nav..

### PR DESCRIPTION
**Pull request by Qodestackr**

### CODE REVIEW

**Comment by Qodestackr** [comment]
Cloned the repo but couldn't find a logo so I've just included a name :+1: (to be changed)

**Comment by Mutinda-Kioko** [comment]
> Cloned the repo but couldn't find a logo so I've just included a name :+1: (to be changed)

There is a logo.tsx file already.......and an exported icon in the images ......

**Comment by Qodestackr** [comment]
> > Cloned the repo but couldn't find a logo so I've just included a name +1 (to be changed)
> 
> There is a logo.tsx file already.......and an exported icon in the images ......

My bad. Didn't check the open PR [here](https://github.com/Kukuza/wakala-web-app/pull/102). Hey but all this are unmerged so when I clone the repo(`dev branch`) I can't access those.

**Comment by Mutinda-Kioko** [comment]
> > > Cloned the repo but couldn't find a logo so I've just included a name +1 (to be changed)
> > 
> > There is a logo.tsx file already.......and an exported icon in the images ......
> 
> My bad. Didn't check the open PR [here](https://github.com/Kukuza/wakala-web-app/pull/102). Hey but all this are unmerged so when I clone the repo(`dev branch`) I can't access those.

There is an images folder from the dev branch.....

**Comment by Qodestackr** [comment]
Sure I see. Don't merge this first, I'll make some changes on icons and such 💯

**Pull request closed without merging**
