### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by vkamunya**

### CODE REVIEW

**Comment by steffenkrogmann** [comment]
@vkamunya 

1. Always add all 4 reviewers to your PR: allen, alphonce, john, and me.

2. Give your PRs a descriptive name and ideally an additional message/description about what the PR is about.

**Review by Allen-Muhani — APPROVED** [review]

**Comment by Alphonce-Mutebi** [comment]
@vkamunya  pull @Mutinda-Kioko  code and use tailwinds

**Comment by steffenkrogmann** [comment]
@vkamunya @Alphonce-Mutebi @Allen-Muhani what is the status here? Still initial commit and not merged?

**Comment by Mutinda-Kioko** [comment]
Closed this since its no longer in context or useful...

**Pull request closed without merging**
